# production / deployment / clean testing enviroment setup

version: '2'
services:

  web:
    ports:
      # Expose Emoncms to the world on port 80
      - 80:80
    volumes:
      # Disable access to /php-info.php for security reasons
      - /dev/null:/var/www/html/php-info.php
    env_file:
     # Use .env with secure db credentials (needs creating), ignored by git
     - '.docker-env'
    restart: always
    environment:
      # Set production enviroment variable flag, not currently used for anything but might be of use in the future
      PRODUCTION: 'true'
    
  db:
    restart: always
    env_file:
     - '.docker-env'
  
